<?php

use Application\Controller\DesignController;
?>
<div class="main-wrapper contact-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <?php echo DesignController::mainTitle('CONTACT US'); ?>
            </div>
            <div class="col-md-12">
                <div class="map-wrapper">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13247.651295378178!2d35.554287831635335!3d33.891898940395805!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x151f161f0aa997e9%3A0xc2a08f3c2235094c!2sJdeideh!5e0!3m2!1sen!2slb!4v1623028754827!5m2!1sen!2slb" width="100%" height="300px" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                </div>
            </div>

            <div class="col-md-12">
                <?php echo DesignController::secondaryTitle('Contact Us Form'); ?>
                <div class="form-wrapper">
                    <div class="notice-area"></div>
                    <form action="<?php echo MAIN_URL . 'contact-submit'; ?>" id="contact-submit">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="name">Full Name*</label>
                                    <input type="text" class="form-control" placeholder="Enter Name" id="name" value="" name="full-name">
                                </div>
                                <div class="col-md-4">
                                    <label for="mobile">Mobile*</label>
                                    <input type="text" class="form-control" placeholder="Enter Mobile" id="mobile" value="" name="mobile">
                                </div>
                                <div class="col-md-4">
                                    <label for="email">Email Address*</label>
                                    <input type="email" class="form-control" placeholder="Enter Email" id="email" value="" name="email">
                            </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="email">Message*</label>
                            <textarea class="form-control" style="min-height: 150px;" name="message"></textarea>
                        </div>
                        <div class="text-left order-complete-btn-wrap">
                            <button type="submit" class="btn submit-btn">SEND</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>