<?php

use Application\Controller\DesignController;
use Application\Controller\HelperController;

?>
<div class="main-wrapper careers-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <?php echo DesignController::mainTitle('CAREERS'); ?>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row careers-header">
            <div class="col-md-12 mx-auto">
                <div class="career-search mb-60">
                    <div class="filter-result">

                        <div class="job-box d-md-flex align-items-center justify-content-between mb-30">
                            <div class="job-left my-4 mr-4 d-md-flex align-items-center flex-wrap">
                                <!-- <div class="img-holder mr-md-4 mb-md-0 mb-4 mx-auto mx-md-0 d-md-none d-lg-flex">
                                    FD
                                </div> -->
                                <div class="job-content">
                                    <h5 class="text-center text-md-left">Frontend Developer</h5>
                                    <ul class="d-md-flex flex-wrap text-capitalize ff-open-sans">
                                        <li class="mr-md-4">
                                            Full Time
                                        </li>
                                    </ul>
                                    <div class="d-md-flex flex-wrap">
                                        Lorem ipsum dolor sit detudzdae amet, rcquisc adipiscing elit. Aenean socada commodo
                                        ligaui egets dolor. Nullam quis ante tiam sit ame orci eget erovtiu faucid.
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

                <!-- Pagination -->

                <!-- end pagination -->
            </div>
        </div>

    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <?php echo DesignController::secondaryTitle('Apply'); ?>
                <div class="form-wrapper">
                    <div class="notice-area"></div>
                    <form action="<?php echo MAIN_URL . 'contact-submit'; ?>" id="contact-submit">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="name">First Name*</label>
                                    <input type="text" class="form-control" placeholder="Enter First Name" id="name" value="" name="first-name">
                                </div>
                                <div class="col-md-6">
                                    <label for="name">Last Name*</label>
                                    <input type="text" class="form-control" placeholder="Enter Last Name" id="name" value="" name="last-name">
                                </div>

                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="mobile">Mobile*</label>
                                    <input type="text" class="form-control" placeholder="Enter Mobile" id="mobile" value="" name="mobile">
                                </div>
                                <div class="col-md-6">
                                    <label for="email">Email Address*</label>
                                    <input type="email" class="form-control" placeholder="Enter email" id="email" value="" name="email">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="email">Upload CV*</label>
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" id="customFile" name="excel">
                                            <label class="custom-file-label" id="customFileLabel" for="customFile">File Name</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="email">Cover Letter*</label>
                            <textarea class="form-control" style="min-height: 150px;" name="message"></textarea>
                        </div>
                        <div class="text-left order-complete-btn-wrap">
                            <button type="submit" class="btn submit-btn">SEND</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>