<?php

use Application\Controller\DesignController;
use Application\Controller\HelperController;
?>
<div class="main-wrapper careers-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <?php echo DesignController::mainTitle('CAREERS'); ?>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row careers-header">
            <div class="col-lg-10 mx-auto mb-4">
                <div class="section-title text-center ">
                    <h3 class="top-c-sep">Grow your career with us</h3>
                    <p>Lorem ipsum dolor sit detudzdae amet, rcquisc adipiscing elit. Aenean socada commodo
                        ligaui egets dolor. Nullam quis ante tiam sit ame orci eget erovtiu faucid.</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-10 mx-auto">
                <div class="career-search mb-60">
                    <!-- <form action="#" class="career-form mb-60">
                        <div class="row">
                            <div class="col-md-6 col-lg-3 my-3">
                                <div class="input-group position-relative">
                                    <input type="text" class="form-control" placeholder="Enter Your Keywords" id="keywords">
                                </div>
                            </div>
                            <div class="col-md-6 col-lg-3 my-3">
                                <div class="select-container">
                                    <select class="custom-select">
                                        <option selected="">Location</option>
                                        <option value="1">Jaipur</option>
                                        <option value="2">Pune</option>
                                        <option value="3">Bangalore</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6 col-lg-3 my-3">
                                <div class="select-container">
                                    <select class="custom-select">
                                        <option selected="">Select Job Type</option>
                                        <option value="1">Ui designer</option>
                                        <option value="2">JS developer</option>
                                        <option value="3">Web developer</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6 col-lg-3 my-3">
                                <button type="button" class="btn btn-lg btn-block btn-light btn-custom" id="contact-submit">
                                    Search
                                </button>
                            </div>
                        </div>
                    </form> -->

                    <div class="filter-result">
                        <p class="mb-30 ff-montserrat">Total Job Openings : 4</p>

                        <div class="job-box d-md-flex align-items-center justify-content-between mb-30">
                            <div class="job-left my-4 mr-4 d-md-flex align-items-center flex-wrap">
                                <!-- <div class="img-holder mr-md-4 mb-md-0 mb-4 mx-auto mx-md-0 d-md-none d-lg-flex">
                                    FD
                                </div> -->
                                <div class="job-content">
                                    <h5 class="text-center text-md-left">Frontend Developer</h5>
                                    <ul class="d-md-flex flex-wrap text-capitalize ff-open-sans">
                                        <li class="mr-md-4">
                                            Full Time
                                        </li>
                                    </ul>
                                    <div class="d-md-flex flex-wrap">
                                    Lorem ipsum dolor sit detudzdae amet, rcquisc adipiscing elit. Aenean socada commodo
                                        ligaui egets dolor. Nullam quis ante tiam sit ame orci eget erovtiu faucid.
                                    </div>
                                </div>
                            </div>
                            <div class="job-right my-4 flex-shrink-0">
                                <a href="<?php echo MAIN_URL.'career/1'?>" class="btn d-block w-100 d-sm-inline-block btn-light">Apply now</a>
                            </div>
                        </div>

                        <div class="job-box d-md-flex align-items-center justify-content-between mb-30">
                            <div class="job-left my-4 mr-4 d-md-flex align-items-center flex-wrap">
                                <!-- <div class="img-holder mr-md-4 mb-md-0 mb-4 mx-auto mx-md-0 d-md-none d-lg-flex">
                                    FD
                                </div> -->
                                <div class="job-content">
                                    <h5 class="text-center text-md-left">Frontend Developer</h5>
                                    <ul class="d-md-flex flex-wrap text-capitalize ff-open-sans">
                                        <li class="mr-md-4">
                                            Part Time
                                        </li>
                                    </ul>
                                    <div class="d-md-flex flex-wrap">
                                    Lorem ipsum dolor sit detudzdae amet, rcquisc adipiscing elit. Aenean socada commodo
                                        ligaui egets dolor. Nullam quis ante tiam sit ame orci eget erovtiu faucid.
                                    </div>
                                </div>
                            </div>
                            <div class="job-right my-4 flex-shrink-0">
                                <a href="<?php echo MAIN_URL.'career/1'?>" class="btn d-block w-100 d-sm-inline-block btn-light">Apply now</a>
                            </div>
                        </div>

                        <div class="job-box d-md-flex align-items-center justify-content-between mb-30">
                            <div class="job-left my-4 mr-4 d-md-flex align-items-center flex-wrap">
                                <!-- <div class="img-holder mr-md-4 mb-md-0 mb-4 mx-auto mx-md-0 d-md-none d-lg-flex">
                                    FD
                                </div> -->
                                <div class="job-content">
                                    <h5 class="text-center text-md-left">UX Designer</h5>
                                    <ul class="d-md-flex flex-wrap text-capitalize ff-open-sans">
                                        <li class="mr-md-4">
                                            Full Time
                                        </li>
                                    </ul>
                                    <div class="d-md-flex flex-wrap">
                                    Lorem ipsum dolor sit detudzdae amet, rcquisc adipiscing elit. Aenean socada commodo
                                        ligaui egets dolor. Nullam quis ante tiam sit ame orci eget erovtiu faucid.
                                    </div>
                                </div>
                            </div>
                            <div class="job-right my-4 flex-shrink-0">
                                <a href="<?php echo MAIN_URL.'career/1'?>" class="btn d-block w-100 d-sm-inline-block btn-light">Apply now</a>
                            </div>
                        </div>

                        <div class="job-box d-md-flex align-items-center justify-content-between mb-30">
                            <div class="job-left my-4 mr-4 d-md-flex align-items-center flex-wrap">
                                <!-- <div class="img-holder mr-md-4 mb-md-0 mb-4 mx-auto mx-md-0 d-md-none d-lg-flex">
                                    FD
                                </div> -->
                                <div class="job-content">
                                    <h5 class="text-center text-md-left">Content Creator</h5>
                                    <ul class="d-md-flex flex-wrap text-capitalize ff-open-sans">
                                        <li class="mr-md-4">
                                            Full Time
                                        </li>
                                    </ul>
                                    <div class="d-md-flex flex-wrap">
                                    Lorem ipsum dolor sit detudzdae amet, rcquisc adipiscing elit. Aenean socada commodo
                                        ligaui egets dolor. Nullam quis ante tiam sit ame orci eget erovtiu faucid.
                                    </div>
                                </div>
                            </div>
                            <div class="job-right my-4 flex-shrink-0">
                                <a href="<?php echo MAIN_URL.'career/1'?>" class="btn d-block w-100 d-sm-inline-block btn-light">Apply now</a>
                            </div>
                        </div>

                    </div>
                </div>

                <!-- Pagination -->

                <!-- end pagination -->
            </div>
        </div>

    </div>
</div>