<?php

use Application\Controller\DesignController;

$title = $categoryName = "All Products";
$itemCategoryMySqlExtDAO = new ItemCategoryMySqlExtDAO();
if($this->isSearch){
    $title = "Search Result";
    $description = "Looking for items with keyword: <b>". $_GET['search'] .'</b>'; 
} else{
    if($this->cat1){
        $categoryInfo = $itemCategoryMySqlExtDAO->queryBySlug($this->cat1);
        $title = $categoryInfo[0]->name;
        $description = "Shop the latest ".strtolower($title)." products in the market";
        $categoryName = $title;
    }
}
if($this->cat2){
    $categoryInfo2 = $itemCategoryMySqlExtDAO->queryBySlug($this->cat2);
    $title2 = $categoryInfo2[0]->name;
    $categoryName = $title2;
}
if($this->cat3){
    $categoryInfo3 = $itemCategoryMySqlExtDAO->queryBySlug($this->cat3);
    $title3 = $categoryInfo3[0]->name;
    $categoryName = $title3;
}
?>
<div class="main-wrapper pb30">
    <div class="small-banner-container with-breadcrumb">
        <div class="small-banner_img">
            <img src="img/small-banner.jpg" />
        </div>
        <div class="small-banner-caption-container">
            <div class="container">
                <div class="banner-title"><?php echo $title;?></div>
                <div class="banner-brief"><?php echo $description;?></div>
            </div>
        </div>
        <div class="banner-breadcrumb">
            <div class="container">
                <ul>
                    <li><a href="<?php echo MAIN_URL;?>"><span><img src="img/home-icon.jpg" /></span>Home</a></li>
                    <li><a><?php echo $categoryName;?></a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="breadcrumb-c d-block d-sm-none">
        <div class="breadcrumb-c-inner">
            <div class="container">
                <ul>
                    <li><a href="<?php echo MAIN_URL;?>"><span><img src="img/home-icon.jpg" /></span>Home</a></li>
                    <li><a><?php echo $categoryName;?></a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="accordion-c">
                    <div class="accordion_title">Filter by</div>
                    <div id="accordion">

                        <div class="card">
                            <div class="card-header">
                                <a class="card-link" data-toggle="collapse" href="#collapseOne">
                                    Category<i class="fas fa-plus"></i>
                                </a>
                            </div>
                            <div id="collapseOne" class="collapse" data-parent="#accordion">
                                <div class="card-body">
                                    Lorem ipsum..
                                </div>
                            </div>
                        </div>

                        <div class="card">
                            <div class="card-header">
                                <a class="collapsed card-link" data-toggle="collapse" href="#collapseTwo">
                                    Price<i class="fas fa-plus"></i>
                                </a>
                            </div>
                            <div id="collapseTwo" class="collapse" data-parent="#accordion">
                                <div class="card-body">
                                    Lorem ipsum..
                                </div>
                            </div>
                        </div>

                        <div class="card">
                            <div class="card-header">
                                <a class="collapsed card-link" data-toggle="collapse" href="#collapseThree">
                                    Brand<i class="fas fa-plus"></i>
                                </a>
                            </div>
                            <div id="collapseThree" class="collapse" data-parent="#accordion">
                                <div class="card-body">
                                    Lorem ipsum..
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
            <div class="col-md-9">
                <div class="row">
                    <?php if ($this->items) { ?>
                        <?php foreach ($this->items as $item) { ?>
                            <div class="col-md-3 col-6 item-col">
                                <?php echo DesignController::item($item); ?>
                            </div>
                        <?php } ?>
                        <div class="col-md-12">
                            <div id="product-pagination" class="product-pagination text-center"></div>
                        </div>
                    <?php } else { ?>
                        <div class="col-md-12"><h3 style="text-align: center;display: block;margin-top: 30px;">No Items Found</h3></div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function() {
        //alert('s');
        //Pagination
        $("#product-pagination").twbsPagination({
            totalPages: <?php echo $this->totalPages; ?>,
            visiblePages: 5,
            first: "",
            last: "",
            next: '<i class="fas fa-chevron-right"></i>',
            prev: '<i class="fas fa-chevron-left"></i>',
            startPage: <?php echo $this->currentPage; ?>,
            initiateStartPageClick: false,
            onPageClick: function(event, page) {
                location.href = '<?php echo MAIN_URL . 'products' . $this->completeSlug . "/?page="; ?>' + page;
            },
        });
    });
</script>