<?php

use Application\Controller\DesignController;
use Application\Controller\HelperController;

?>
<div class="main-wrapper">
    <div class="small-banner-container with-breadcrumb">
        <div class="small-banner_img">
            <img src="img/banner-red.jpg" />
        </div>
        <div class="small-banner-caption-container centered">
            <div class="container">
                <div class="banner-title1"><?php echo strtoupper(_t('todaysDeals'));?></div>
                <div class="banner-title2"><?php echo _t('getReady');?></div>
                <div class="banner-title3"><?php echo _t('getChance');?></div>
            </div>
        </div>
        <div class="banner-breadcrumb">
            <div class="container">
                <ul>
                    <li><a href="<?php echo MAIN_URL; ?>"><span><img src="img/home-icon.jpg" /></span><?php echo _t('home')?></a></li>
                    <li><a class="light"><?php echo _t('todaysDeals')?></a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="breadcrumb-c d-block d-sm-none">
        <div class="breadcrumb-c-inner">
            <div class="container">
                <ul>
                    <li><a href="<?php echo MAIN_URL; ?>"><span><img src="img/home-icon.jpg" /></span>Home</a></li>
                    <li><a class=""><?php echo _t('todaysDeals');?></a></li>
                </ul>
            </div>
        </div>
    </div>
    <?php if ($this->spotlight) {
        $percentage = round(100 - ($this->spotlight->salePrice/$this->spotlight->regularPrice) * 100);
        $href = MAIN_URL . 'product/' . $this->spotlight->slug;
        $title = $this->spotlight->title;
        $imageUrl = ($this->spotlight->image !="" && $this->spotlight->image != null) ? HelperController::getImageUrl($this->spotlight->image) : PRODUCT_PLACEHOLDER_IMAGE_URL;?>
        <div class="spotlight-deals">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 d-block d-sm-none">
                        <div class="spotlight-deals_title">SPOTLIGHT DEALS <span><a href="<?php echo $href;; ?>">
                                    <img src="img/arrow-right-grey.png" /></a></span>
                        </div>
                    </div>
                    <div class="col-md-4 spotlight-deals_img">
                        <div class="sale-tag"><?php echo $percentage;?>%</div>
                        <a href="<?php echo $href; ?>">
                            <img src="<?php echo $imageUrl;?>" />
                        </a>
                    </div>
                    <div class="col-md-8">
                        <div class="spotlight-deals_title d-none d-sm-block"><?php echo strtoupper(_t('spotlightDeals'));?>
                            <span><a href="<?php echo $href; ?>"><img src="img/arrow-<?php echo _t('config')['right'];?>-grey.png" /></a></span>
                        </div>
                        <div class="spotlight-deals_item_title">
                            <a href="<?php echo $href; ?>">
                                <?php echo $title; ?>
                            </a>
                        </div>
                        <div class="spotlight-deals_price1"><?php echo number_format($this->spotlight->regularPrice)?></div>
                        <div class="spotlight-deals_price2"><?php echo number_format($this->spotlight->salePrice);?> <span><?php echo _t('lbp');?></span></div>
                        <div class="spotlight-deals_buttons">
                            <a href="javascript:void(0);" class="add-to-wishlist wishlist-add" data-item-id="<?php echo $this->spotlight->id;?>"><img src="img/heart-off.png" /><?php echo _t('addToWishlist');?></a>
                            <a href="javascript:void(0);" class="add-to-wishlist"><img src="img/cart.png" /><?php echo _t('addToCart');?></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
    <div class="container">
        <div class="row">
            <div class="col-md-12 with-margin">
                <?php echo DesignController::mainTitle(strtoupper(_t('todaysDeals'))) ?>
            </div>
        </div>
        <div class="row">
            <?php ?>
            <?php foreach ($this->items as $item) { ?>
                <div class="col-6 col-md-2 item-col">
                    <?php echo DesignController::item($item); ?>
                </div>
            <?php } ?>

        </div>

        <div class="row">
            <div class="col-md-12">
                <div id="product-pagination" class="product-pagination text-center"></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function() {
        //alert('s');
        //Pagination
        $("#product-pagination").twbsPagination({
            totalPages: <?php echo $this->totalPages; ?>,
            visiblePages: 5,
            first: '<i class="fas fa-angle-double-'+translations.config.left+'"></i>',
            last: '<i class="fas fa-angle-double-'+translations.config.right+'"></i>',
            next: '<i class="fas fa-chevron-'+translations.config.right+'"></i>',
            prev: '<i class="fas fa-chevron-'+translations.config.left+'"></i>',
            startPage: <?php echo $this->currentPage; ?>,
            initiateStartPageClick: false,
            onPageClick: function(event, page) {
                location.href = '<?php echo MAIN_URL . 'todays-deals' . "/?page="; ?>' + page;
            },
        });
    });
</script>