<!-- The Modal -->
<div class="modal" id="add-warehouse-modal">

    <div class="modal-dialog modal-xl">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <div class="modal-title">Add new warehouse!</div>
                <div class="modal-subtitle">Add new warehuse to manage your stock.</div>

                <div class="vendor-page-wrapper">
                    <form action="/action_page.php">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6 input-wrap">
                                    <div class="row">
                                        <div class="col-md-4 pr0">
                                            <label for="email">*First Name</label>
                                        </div>
                                        <div class="col-md-8">
                                            <input type="text" class="form-control" placeholder="">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6 input-wrap">
                                    <div class="row">
                                        <div class="col-md-4 pr0">
                                            <label for="email">*Last Name</label>
                                        </div>
                                        <div class="col-md-8">
                                            <input type="text" class="form-control" placeholder="">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6 input-wrap">
                                    <div class="row">
                                        <div class="col-md-4 pr0">
                                            <label for="email">*Email Address</label>
                                        </div>
                                        <div class="col-md-8">
                                            <input type="email" class="form-control" placeholder="">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6 input-wrap">
                                    <div class="row">
                                        <div class="col-md-4 pr0">
                                            <label for="email">*Mobile Number</label>
                                        </div>
                                        <div class="col-md-8">
                                            <input type="text" class="form-control" placeholder="" id="mobile-number" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6 input-wrap">
                                    <div class="row">
                                        <div class="col-md-4 pr0">
                                            <label for="email">Warehouse Name</label>
                                        </div>
                                        <div class="col-md-8">
                                            <input type="text" class="form-control" placeholder="">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn submit-btn">SAVE</button>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>