<!-- The Modal -->
<div class="modal" id="login-modal">

    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <div class="modal-title">Welcome Back!</div>
                <div class="modal-subtitle">To stay connected with us, please login<br>with your
                    personal information</div>

                <div class="modal-form">
                    <form action="/action_page.php">
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Email address*" id="email">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" placeholder="Enter password" id="pwd">
                            <span class="forgot"><a href="#">Forgot password?</a></span>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" type="checkbox"> Remember me
                            </label>
                        </div>
                        <!-- <div class="form-group">
                            <div id="my-signin2"></div>
                        </div>
                        <div class="form-group" id="fb-login-button">
                            <div class="fb-login-button" data-width="" data-size="large" data-button-type="login_with" data-layout="default" data-auto-logout-link="false" data-use-continue-as="false"></div>
                        </div> -->
                        <div class="centered-button">
                            <button type="submit" class="btn btn-primary">SIGN IN</button>
                        </div>
                        <div class="have-account">
                            <p>Don't have an account yet</p>
                            <!-- Button to Open the Modal -->
                            <a class="modal-register" data-toggle="modal" data-target="#signup-modal" data-dismiss="modal">
                                Register
                            </a>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </div>
</div>