<?php

use Application\Controller\FacebookController;
use Application\Controller\HelperController;

?>
<!-- The Modal -->
<div class="modal" id="signup-modal">

    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body register-modal-body">
                <div class="modal-title"><?php echo _t('newHere');?></div>
                <div class="modal-subtitle">Join our big family and stay updated with our latest
                    promotions and offers</div>

                <div class="fb-button-wrapper in-register">
                    <a href="<?php echo FacebookController::getLoginUrl(HelperController::getCurrentUrl()); ?>"><i class="fab fa-facebook-f"></i> Register with facebook</a>
                </div>
                <div class="or"><?php echo _t('or');?></div>
                <div class="modal-form">
                    <form action="<?php echo MAIN_URL . 'submit-register' ?>" autocomplete="off" id="register-form">
                        <input type="hidden" name="redirectUrl" value="<?php echo HelperController::getCurrentUrl(); ?>" />
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    <input type="text" class="form-control" name="full-name" placeholder="<?php echo _t('fullName');?>" autocomplete="off">
                                </div>
                                <div class="col-md-6">
                                    <input type="date" class="form-control" name="birthday" placeholder="YYYY-MM-DD" autocomplete="off" />
                                </div>
                            </div>

                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" name="email" placeholder="<?php echo _t('emailAddress');?>*" id="signup-email" autocomplete="off">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" name="password" placeholder="<?php echo _t('enterPassword');?>" id="signup-pwd" autocomplete="off">
                        </div>
                        <div class="form-group">
                            <input type="password" name="confirm-password" class="form-control confirm-password" placeholder="<?php echo _t('confirmPassword');?>" id="pwd" autocomplete="off">
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input name="agree" class="form-check-input" type="checkbox"> I agree on the <a href="<?php echo MAIN_URL.'page/term-conditions'?>" data-toggle="modal" data-target="#terms-modal" data-dismiss="modal">Terms & Conditions</a>
                            </label>
                        </div>
                        <!-- <div class="form-group">
                            <div id="my-signin2"></div>
                        </div>
                        <div class="form-group" id="fb-login-button">
                            <div class="fb-login-button" data-width="" data-size="large" data-button-type="login_with" data-layout="default" data-auto-logout-link="false" data-use-continue-as="false"></div>
                        </div> -->
                        <div class="notice-area"></div>

                        <div class="centered-button">
                            <button type="submit" class="btn signup-button"><?php echo strtoupper(_t('register'));?></button>
                        </div>
                        <div class="have-account">
                            <p><?php echo _t('haveAccount');?></p>
                            <!-- Button to Open the Modal -->
                            <a class="modal-register" data-toggle="modal" data-target="#login-modal" data-dismiss="modal">
                            <?php echo strtoupper(_t('signin'));?>
                            </a>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#register-form").submit(function(e) {
        var formData = new FormData(this);
        var formUrl = $(this).attr('action');
        $.ajax({
            url: formUrl,
            type: 'POST',
            dataType: 'json',
            data: formData,
            mimeType: "multipart/form-data",
            contentType: false,
            cache: false,
            processData: false,
            beforeSend: function() {
                showMsg('.notice-area', true, 'Registering your account, please wait...');
            },
            success: function(response) {
                showMsg('.notice-area', response.status, response.msg);
                if (response.status == true) {
                    location.href = response.redirectUrl;
                }
            },
            error: function() {
                showMsg('.notice-area', false, 'An error occured, please try again!');
            }
        });
        e.preventDefault();
    });
</script>