<!-- The Modal -->
<div class="modal" id="signup-modal">

    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body register-modal-body">
                <div class="modal-title">Im new here!</div>
                <div class="modal-subtitle">Join our big family and stay updated with our latest
                    promotions and offers</div>
                <div class="modal-form">
                    <form action="/action_page.php" autocomplete="off">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    <input type="text" class="form-control" name="full-name" placeholder="Full Name" autocomplete="off">
                                </div>
                                <div class="col-md-6">
                                    <input type="date" class="form-control" name="birthday" placeholder="YYYY-MM-DD" autocomplete="off" />
                                </div>
                            </div>

                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Email address*" id="email" autocomplete="off">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" placeholder="Enter password" id="pwd" autocomplete="off">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control confirm-password" placeholder="Confirm password" id="pwd" autocomplete="off">
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" type="checkbox"> I agree on the <a href="http://google.com">Terms & Conditions</a>
                            </label>
                        </div>
                        <!-- <div class="form-group">
                            <div id="my-signin2"></div>
                        </div>
                        <div class="form-group" id="fb-login-button">
                            <div class="fb-login-button" data-width="" data-size="large" data-button-type="login_with" data-layout="default" data-auto-logout-link="false" data-use-continue-as="false"></div>
                        </div> -->
                        
                        <div class="centered-button">
                            <button type="submit" class="btn btn-primary signup-button">SIGN IN</button>
                        </div>
                        <div class="have-account">
                            <p>Already have an account?</p>
                            <!-- Button to Open the Modal -->
                            <a class="modal-register" data-toggle="modal" data-target="#login-modal" data-dismiss="modal">
                                Login
                            </a>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </div>
</div>