<div class="main-banner-container">
<div class="" id="main-banner">
  <div>
      <div class="banner-item">
        <div class="banner-item_img"><img src="img/banner.png" title="Funky roots"></div>
        <div class="banner-item_caption1">UP TO 60%</div>
        <div class="banner-item_caption2">Happy mother's day</div>
        <div class="banner-item_button"><a href="#">START SHOPPING</a></div>
      </div>
  </div>
  <div>
      <div class="banner-item">
        <div class="banner-item_img"><img src="img/banner.png" title="Funky roots"></div>
        <div class="banner-item_caption1">UP TO 60%</div>
        <div class="banner-item_caption2">Happy mother's day</div>
        <div class="banner-item_button"><a href="#">START SHOPPING</a></div>
      </div>
  </div>
  <div>
      <div class="banner-item">
        <div class="banner-item_img"><img src="img/banner.png" title="Funky roots"></div>
        <div class="banner-item_caption1">UP TO 60%</div>
        <div class="banner-item_caption2">Happy mother's day</div>
        <div class="banner-item_button"><a href="#">START SHOPPING</a></div>
      </div>
  </div>
</div>
</div>