<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12 footer1">
                <div class="row">
                    <div class="col-md-3">
                        <div class="logo-social">
                            <div class="footer-logo">
                                <img src="img/logo.png" />
                            </div>
                            <div class="social-media">
                                <a href="#"><img src="img/fb.png" /></a>
                                <a href="#"><img src="img/insta.png" /></a>
                                <a href="#"><img src="img/twitter.png" /></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-6 footer-menu">
                        <div class="footer-menu_title">we are...</div>
                        <ul>
                            <li><a href="#">About us</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">Contact us</a></li>
                            <li><a href="#">Terms & conditions</a></li>
                            <li><a href="#">FAQ's</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-6 footer-menu">
                        <div class="footer-menu_title">we are...</div>
                        <ul>
                            <li><a href="#">About us</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">Contact us</a></li>
                            <li><a href="#">Terms & conditions</a></li>
                            <li><a href="#">FAQ's</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 footer-menu">
                        <div class="footer-menu_title">we are...</div>
                        <ul>
                            <li><a href="#">About us</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">Contact us</a></li>
                            <li><a href="#">Terms & conditions</a></li>
                            <li><a href="#">FAQ's</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-12 footer2">
                <p>Mastershop &copy; <?= date('Y') ?> All rights reserved, powered by <a href="http://thirteencube.com" target="_blank">Thirteencube</a></p>
            </div>
        </div>
    </div>
</footer>