<?php 
$contentMySqlExtDAO = new ContentMySqlExtDAO();
$facebook = $contentMySqlExtDAO->queryBySlug('facebook')[0];
$instagram = $contentMySqlExtDAO->queryBySlug('instagram')[0];
?>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12 footer1">
                <div class="row">
                    <div class="col-md-3">
                        <div class="logo-social">
                            <div class="footer-logo">
                                <img src="img/logo.png?v=1.0.0" />
                            </div>
                            <div class="social-media">
                                <a href="<?php echo $facebook->customUrl;?>" target="_blank"><img src="img/fb.png" /></a>
                                <a href="<?php echo $instagram->customUrl;?>" target="_blank"><img src="img/insta.png" /></a>
                                <!-- <a href="https://twitter.com" target="_blank"><img src="img/twitter.png" /></a> -->
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-6 footer-menu">
                        <div class="footer-menu_title">we are...</div>
                        <ul>
                            <li><a href="<?php echo MAIN_URL . 'page/about-us' ?>">About us</a></li>
                            <li><a href="<?php echo MAIN_URL . 'careers'?>">Careers</a></li>
                            <li><a href="<?php echo MAIN_URL . 'contact-us'?>">Contact us</a></li>
                            <li><a href="<?php echo MAIN_URL . 'page/terms-conditions' ?>">Terms & conditions</a></li>
                            <li><a href="<?php echo MAIN_URL . 'page/frequently-asked-questions' ?>">FAQ's</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-6 footer-menu">
                        <div class="footer-menu_title">more about us...</div>
                        <ul>
                            <!-- <li><a href="javascript:void(0);">News/Events</a></li> -->
                            <li><a href="<?php echo MAIN_URL . 'promotions' ?>">Promotions</a></li>
                            <li><a href="<?php echo MAIN_URL . 'latest-arrivals' ?>">Latest Arrivals</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 footer-menu">
                        <div class="footer-menu_title">my account...</div>
                        <ul>
                            <li><a href="javascript:void(0);" data-toggle="modal" data-target="#login-modal">Sign In</a></li>
                            <li><a href="<?php echo MAIN_URL . 'my-cart'; ?>">My Cart</a></li>
                            <li><a href="<?php echo MAIN_URL . 'my-wishlist'; ?>">My Wishlist</a></li>
                            <li><a href="<?php echo MAIN_URL . 'page/return-policy'; ?>">Return Policy</a></li>
                            <li><a href="<?php echo MAIN_URL . 'page/warranty'; ?>">Warranty</a></li>
                            <li><a href="<?php echo MAIN_URL . 'vendor-login'; ?>">Vendor Area</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-12 footer2">
                <p>Mastershop &copy; <?= date('Y') ?> All rights reserved, powered by <a href="http://thirteencube.com" target="_blank">Thirteencube</a></p>
            </div>
        </div>
    </div>
    <div class="floating-wpp"></div>
</footer>
<?php /*<pre>
    <?php print_r($_SESSION['user']);?>
</pre>*/?>