<?php

use Application\Controller\LanguageController;

$contentMySqlExtDAO = new ContentMySqlExtDAO();
$facebook = $contentMySqlExtDAO->queryBySlug('facebook')[0];
$instagram = $contentMySqlExtDAO->queryBySlug('instagram')[0];
$lang = LanguageController::getLanguage();
?>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12 footer1">
                <div class="row">
                    <div class="col-md-3">
                        <div class="logo-social">
                            <div class="footer-logo">
                                <img src="img/logo.png?v=1.0.0" />
                            </div>
                            <div class="social-media">
                                <a href="<?php echo $facebook->customUrl; ?>" target="_blank"><img src="img/fb.png" /></a>
                                <a href="<?php echo $instagram->customUrl; ?>" target="_blank"><img src="img/insta.png" /></a>
                                <!-- <a href="https://twitter.com" target="_blank"><img src="img/twitter.png" /></a> -->
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-6 footer-menu">
                        <div class="footer-menu_title"><?php echo _t('weAre...');?></div>
                        <ul>
                            <li><a href="<?php echo MAIN_URL . $lang. '/page/about-us' ?>"><?php echo _t('aboutUs');?></a></li>
                            <li><a href="<?php echo MAIN_URL . $lang . '/careers' ?>"><?php echo _t('careers');?></a></li>
                            <li><a href="<?php echo MAIN_URL . $lang . '/contact-us' ?>"><?php echo _t('contactUs');?></a></li>
                            <li><a href="<?php echo MAIN_URL . $lang . '/page/terms-conditions' ?>"><?php echo _t('termsAndConditions');?></a></li>
                            <li><a href="<?php echo MAIN_URL . $lang . '/page/frequently-asked-questions' ?>"><?php echo _t('faqs');?></a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-6 footer-menu">
                        <div class="footer-menu_title"><?php echo _t('moreAboutUs...');?></div>
                        <ul>
                            <!-- <li style="display: none;"><a href="javascript:void(0);">News/Events</a></li> -->
                            <li><a href="<?php echo MAIN_URL . $lang . '/promotions' ?>"><?php echo _t('promotions');?></a></li>
                            <li><a href="<?php echo MAIN_URL . $lang . '/latest-arrivals' ?>"><?php echo _t('latestProducts');?></a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 footer-menu">
                        <div class="footer-menu_title"><?php echo _t('myAccount...');?></div>
                        <ul>
                            <li><a href="javascript:void(0);" data-toggle="modal" data-target="#login-modal"><?php echo _t('signin');?></a></li>
                            <li><a href="<?php echo MAIN_URL . 'my-cart'; ?>"><?php _t('myCart');?></a></li>
                            <li><a href="<?php echo MAIN_URL . $lang . '/my-wishlist'; ?>"><?php echo _t('myWishlist');?></a></li>
                            <li><a href="<?php echo MAIN_URL . $lang. '/page/return-policy'; ?>"><?php echo _t('returnPolicy');?></a></li>
                            <li><a href="<?php echo MAIN_URL . $lang .'/page/warranty'; ?>"><?php echo _t('warranty');?></a></li>
                            <li><a href="<?php echo MAIN_URL . 'vendor-login'; ?>"><?php echo _t('vendorArea');?></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-12 footer2">
                <?php 
                $year = date('Y');
                $str = "<a href='http://thirteencube.com' target='_blank'>Thirteencube</a>";
                //$welcome = sprintf('Mastershop &copy; %s All Rights reserved, powered by %s', $number, $str);
                ?>
                <p><?php echo sprintf('Mastershop &copy; %s '._t('allRightsReserved').' %s', $year, $str);?> </p>
            </div>
        </div>
    </div>
    <div class="floating-wpp"></div>
</footer>
<!-- <pre>
    <?php //print_r($_SESSION['lang']); ?>
</pre> -->