<header>
    <div class="upper-menu-container">
        <div class="container">
            <div class="upper-menu">
                <div class="row">
                    <div class="col-md-3 col-6">
                        <div class="signin-register">
                            Hi <a href="#" class="signin">Sign in</a> or <a href="#" class="register">Register</a>
                        </div>
                    </div>
                    <div class="col-md-6 col-6 d-none d-sm-block">
                        <ul class="custom-menu custom-menu-centered">
                            <li><a href="#">Todays Deals</a></li>
                            <li><a href="#">Latest Arrivals</a></li>
                            <li><a href="#">About us</a></li>
                            <li class="dropdown pointer">
                                <a class="dropdown-toggle" data-toggle="dropdown">Help & Contact
                                    <span class="caret"></span></a>
                                <div class="dropdown-menu ">
                                    Dora Highway<br>
                                    Facing Gargour
                                    <span class="small-separator"></span>
                                    +961 1 255 921<br>
                                    +961 1 255 922<br>
                                    +961 3 217 821
                                    <span class="small-separator"></span>
                                    Monday to Friday<br>
                                    8:00 am till 5:00 pm
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-6">
                        <ul class="custom-menu custom-menu-right">
                            <li class="wishlist">
                                <a href="#" class="d-none d-sm-inline-block">my wishlist</a>
                                <a href="#" class="d-inline-block d-sm-none"><i class="far fa-heart"></i></a>
                            </li>
                            <!-- <li class="bell-icon"><a href=""><i class="far fa-bell"></i></a></li> -->
                            <!-- <li class="cart-icon"><a href="#"><i class="fas fa-shopping-cart"></i><span class="badge">5</span></a></li> -->
                            <li class="dropdown pointer cart-icon">
                                <a class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fas fa-shopping-cart"></i><span class="badge">5</span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <form>
                                    <div class="compact-cart-wrapper">
                                        <div class="compact-cart-item">
                                            <div class="row">
                                                <div class="col-md-3 compact-cart-img">
                                                    <img src="img/product.png" />
                                                </div>
                                                <div class="col-md-9">
                                                    <div class="compact-cart-title">
                                                        Tefal Fondue Inox
                                                        Design &
                                                    </div>
                                                    <div class="compact-cart-price">
                                                       1,290,000 LBP
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="compact-cart-item">
                                            <div class="row">
                                                <div class="col-md-3 compact-cart-img">
                                                    <img src="img/product.png" />
                                                </div>
                                                <div class="col-md-9">
                                                    <div class="compact-cart-title">
                                                        Tefal Fondue Inox
                                                        Design &
                                                    </div>
                                                    <div class="compact-cart-price">
                                                       1,290,000 LBP
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="compact-cart-buttons">
                                            <a href="#" class="to-cart">Continue to cart</a>
                                            <a href="#" class="to-checkout">Continue to checkout</a>
                                        </div>
                                    </div>
                                    </form>
                                </div>
                            </li>
                            <li class="dropdown pointer">
                                <a class="dropdown-toggle" data-toggle="dropdown">
                                    <img src="img/uk.png" />
                                    <span class="caret"></span></a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="#"><img src="img/uk.png" /></a></li>
                                    <li><a href="#"><img src="img/leb.png" /></a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">

        <div class="middle-menu clearfix">
            <div class="logo-container">
                <a href="#"><img src="img/logo.png" /></a>
            </div>
            <div class="search-container">
                <div class="input-group">
                    <div class="input-group-prepend all-cat-btn">
                        <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">All <span class="d-none d-sm-inline-block">Categories</span></button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                            <div role="separator" class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Separated link</a>
                        </div>
                    </div>
                    <input type="text" class="form-control" aria-label="All Categories" placeholder="Search for anything">
                    <div class="input-group-append search-button">
                        <button class="btn btn-outline-secondary" type="button">
                            <span class="d-none d-sm-inline-block">SEARCH</span>
                            <i class="fas fa-search d-block d-sm-none"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php echo $this->partial('layout/menu/desktop-menu') ?>
    <?php echo $this->partial('layout/menu/mobile-menu') ?>
</header>