<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
if (defined('RUNNING_FROM_ROOT')) {
    $this->plugin('basePath')->setBasePath($this->basePath() . '/public');
}
?>
<!doctype html>
<?php 
$htmlClass = isset($this->htmlClass) ? $this->htmlClass : '';
?>
<html lang="en" class="<?php echo $htmlClass;?>">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <base href="<?php echo BASE_URL; ?>">
    <link rel="icon" type="image/png" href="img/favicon.png" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@300;400;700&family=Montserrat:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css" crossorigin="anonymous">
    <script src="js/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="fontawesome-free-5.15.3-web/css/all.css">
    <link rel="stylesheet" href="js/bxslider-4-4.2.12/dist/jquery.bxslider.css">
    <!-- Magnific Popup core CSS file -->
    <link rel="stylesheet" href="js/magnific-popup/dist/magnific-popup.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css">
    <!-- Intl tel number CSS-->
    <link rel="stylesheet" href="js/intl-tel-input-master/css/intlTelInput.css">
    <link rel="stylesheet" href="css/all.css" crossorigin="anonymous">
</head>

<body>
    <!--=================================================== HEADER      ===============================================-->
    <?php echo $this->partial('layout/header') ?>
    <!--=================================================== END HEADER  ===============================================-->
    <!--=================================================== Banner      ===============================================-->
    <?php if ($this->withBanner) {
        echo $this->partial('layout/banner');
    } ?>
    <!--=================================================== END Banner  ===============================================-->
    <!-- ================================================== BODY        ============================================== -->
    <?php echo $this->content ?>
    <!-- ================================================== END BODY    ============================================== -->
    <!--=================================================== FOOTER      ===============================================-->
    <?php echo $this->partial('layout/footer'); ?>
    <?php echo $this->partial('layout/modals/login-modal'); ?>
    <?php echo $this->partial('layout/modals/signup-modal'); ?>
    <?php echo $this->partial('layout/modals/add-warehouse-modal'); ?>
    <!--=================================================== END FOOTER  ===============================================-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="js/bxslider-4-4.2.12/dist/jquery.bxslider.min.js"></script>
    <script src="js/twbs-pagination-master/jquery.twbsPagination.min.js"></script>
    <!-- Magnific Popup core JS file -->
    <script src="js/magnific-popup/dist/jquery.magnific-popup.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <script src="js/intl-tel-input-master/js/intlTelInput-jquery.min.js"></script>

    <script src="js/main.js"></script>
    <script src="bootstrap/js/bootstrap.min.js" crossorigin="anonymous"></script>
    
</body>

</html>