<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
if (defined('RUNNING_FROM_ROOT')) {
    $this->plugin('basePath')->setBasePath($this->basePath() . '/public');
}
?>
<!doctype html>
<?php
$date = isset($_GET['date']) ? $_GET['date'] : '';
$htmlClass = isset($this->htmlClass) ? $this->htmlClass : '';
$userCountry = "LB";
$isLoggedIn = false;
$userType = false;
if (isset($_SESSION['user'])) {
    if ($_SESSION['user']->country != "" && $_SESSION['user']->country != null) {
        $userCountry = $_SESSION['user']->country;
    }
    if ($_SESSION['user']->id) {
        $isLoggedIn = true;
        $userType = $_SESSION['user']->userType;
    }
}
?>
<html lang="en" class="<?php echo $htmlClass; ?>">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <base href="<?php echo BASE_URL; ?>">
    <link rel="icon" type="image/png" href="img/favicon.png" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@300;400;700&family=Montserrat:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css" crossorigin="anonymous">
    <script src="js/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="fontawesome-free-5.15.3-web/css/all.css">
    <link rel="stylesheet" href="js/bxslider-4-4.2.12/dist/jquery.bxslider.css">
    <!-- Magnific Popup core CSS file -->
    <link rel="stylesheet" href="js/magnific-popup/dist/magnific-popup.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css">
    <!-- Intl tel number CSS-->
    <link rel="stylesheet" href="js/intl-tel-input-master/css/intlTelInput.css">
    <!-- Whatsapp CSS-->
    <link rel="stylesheet" href="js/whatsapp/floating-wpp.min.css">
    <!-- Alertify CSS -->
    <link rel="stylesheet" href="js/alertifyjs/css/alertify.min.css">
    <link rel="stylesheet" href="css/all.css?v=1.3.0" crossorigin="anonymous">
</head>

<body>
<div class="page-loader"><span><i class="fas fa-spinner fa-spin"></i></span></div>
    <!--=================================================== HEADER      ===============================================-->
    <?php echo $this->partial('layout/header') ?>
    <!--=================================================== END HEADER  ===============================================-->
    <!--=================================================== Banner      ===============================================-->
    <?php if ($this->withBanner) {
    echo $this->partial('layout/banner');
} ?>
    <!--=================================================== END Banner  ===============================================-->
    <!-- ================================================== BODY        ============================================== -->
    <?php echo $this->content ?>
    <!-- ================================================== END BODY    ============================================== -->
    <!--=================================================== FOOTER      ===============================================-->
    <?php echo $this->partial('layout/footer'); ?>
    <?php echo $this->partial('layout/modals/login-modal'); ?>
    <?php echo $this->partial('layout/modals/signup-modal'); ?>
    <?php echo $this->partial('layout/modals/add-warehouse-modal'); ?>
    <?php echo $this->partial('layout/modals/edit-warehouse-modal'); ?>
    <?php echo $this->partial('layout/modals/terms-modal'); ?>
    <!--=================================================== END FOOTER  ===============================================-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="js/bxslider-4-4.2.12/dist/jquery.bxslider.js"></script>
    <script src="js/twbs-pagination-master/jquery.twbsPagination.min.js"></script>
    <!-- Magnific Popup core JS file -->
    <script src="js/magnific-popup/dist/jquery.magnific-popup.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <script src="js/intl-tel-input-master/js/intlTelInput-jquery.min.js"></script>
    <!-- Whatsapp JS-->
    <script src="js/whatsapp/floating-wpp.min.js"></script>
    <!-- Alertify JS-->
    <script src="js/alertifyjs/alertify.min.js"></script>

    <script src="bootstrap/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <script src="js/main.js?v=1.3.0"></script>
    <script type="text/javascript">
        const mainUrl = '<?php echo MAIN_URL; ?>';
        const userCountry = '<?php echo $userCountry; ?>';
        const isLoggedIn = '<?php echo $isLoggedIn; ?>';
        const userType = '<?php echo $userType; ?>';
        const useNewMechanism = '<?php echo boolval(USE_NEW_IMPORT_MECHANISM);?>';
        $(function() {
            <?php if ($date == "") { ?>
                $('.date').val('');
            <?php } ?>
        });
    </script>

</body>

</html>