<?php

use Application\Controller\DesignController;

?>
<div class="main-wrapper shopping-cart pt30">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <?php echo DesignController::mainTitle('CHECKOUT') ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <table class="table shopping-cart-wrap checkout-wrap">
                    <thead class="text-muted">
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col" class="text-right">Sub Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $total = 0;
                        foreach ($this->items as $item) {
                            $item = DesignController::checkOutItem($item);
                            $total += $item->subtotal;
                            echo $item->html;
                        } ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td class="text-right cart-total">Total</td>
                            <td class="text-right" id="cart-total"><?php echo number_format($total) . " LBP"; ?></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <div class="col-md-4">
                <div class="checkout-form-wrapper">
                    <form action="/action_page.php">
                        <div class="form-group">
                            <label for="name">Full Name *</label>
                            <input type="text" class="form-control" placeholder="Enter Name" id="name" value="<?php echo $_SESSION['user']->fullName?>">
                        </div>
                        <div class="form-group">
                            <label for="mobile">Mobile *</label>
                            <input type="text" class="form-control" placeholder="Enter Mobile" id="mobile" value="<?php echo $_SESSION['user']->mobile?>">
                        </div>
                        <div class="form-group">
                            <label for="email">Email Address: *</label>
                            <input type="email" class="form-control" placeholder="Enter email" id="email" value="<?php echo $_SESSION['user']->email?>">
                        </div>
                        <div class="form-group">
                            <label for="email">Delivery Address: *</label>
                            <textarea class="form-control" style="min-height: 200px;" name="delivery-address"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="email">Notes:</label>
                            <textarea class="form-control" style="min-height: 200px;" name="notes"></textarea>
                        </div>
                        <button type="submit" class="btn submit-btn">Complete Order</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>