<?php

?>
<div class="main-wrapper forgot-password pt30">
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <!-- Modal body -->
                <div class="modal-body">
                    <div class="modal-title">Forgot Password ?</div>
                    <div class="modal-subtitle">Don't worry, enter your email and we will send you a link to reset your password.</div>

                    <div class="modal-form">
                        <form action="<?php echo MAIN_URL . 'forgot-password-submit/' . $this->userType; ?>" id="forgot-form">
                            <div class="notice-area"></div>
                            <div class="form-group">
                                <input type="email" class="form-control" placeholder="Email address*" id="login-email" name="email" autocomplete="username">
                            </div>
                            <div class="centered-button">
                                <button type="submit" class="btn">SEND RESET LINK</button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<?php //$redirectUrl = urlencode($_GET['redirectUrl']);
?>
<script>
    // const redirectUrl = '<?php //echo $redirectUrl;
                            ?>';
    // $(function(){
    //     $('input[name="redirectUrl"]').val(redirectUrl);
    // });
</script>