<?php

use Application\Controller\DesignController;
use Application\Controller\LanguageController;

$lang = LanguageController::getLanguage();
?>
<div class="main-wrapper shopping-cart pt30">
    <div class="container">
        <?php if ($this->items) { ?>
            <div class="card">
                <table class="table table-hover shopping-cart-wrap">
                    <thead class="text-muted">
                        <tr>
                            <th scope="col"></th>
                            <th scope="col"><?php echo _t('product'); ?></th>
                            <th scope="col" width="200"><?php echo _t('price'); ?></th>
                            <th scope="col" width="200"><?php echo _t('qty'); ?></th>
                            <th scope="col" width="200"><?php echo _t('subtotal'); ?></th>
                            <th scope="col" width="200" class="text-right"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $total = 0;
                        foreach ($this->items as $item) {
                            $item = DesignController::cartItem($item);
                            $total += $item->subtotal;
                            echo $item->html;
                        } ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td class="text-right cart-total" colspan="5">Total</td>
                            <td class="text-right" id="cart-total"><?php echo number_format($total) . " " . _t('lbp'); ?></td>
                        </tr>
                    </tfoot>
                </table>
            </div> <!-- card.// -->

        <?php } else { ?>
            <h3 style="display: block; text-align: center;margin-top: 3rem;">Your Cart Is Empty</h3>
            <div class="go-shopping">
                <a href="<?php echo MAIN_URL . $lang . '/products' ?>">Go Shopping</a>
            </div>
        <?php } ?>

    </div>
    <!--container end.//-->
    <?php if ($this->items) { ?>
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-right checkout-btn-wrap">
                    <a href="<?php echo MAIN_URL . $lang . '/checkout'; ?>" class="" id="checkout-btn"><?php echo _t('continueCheckout'); ?></a>
                </div>
            </div>
        </div>

    <?php } ?>
</div>