<?php

use Application\Controller\DesignController;
use Application\Controller\ProductController;
?>
<div class="main-wrapper pt30">
    <div class="container mb-4">
        <div class="row">
            <div class="col-lg-4 pb-5">
                <!-- Account Sidebar-->
                <div class="author-card pb-3">
                    <div class="author-card-cover" style="background-image: url(<?php echo USER_AVATAR_BG_URL; ?>);">
                        <!-- <a class="btn btn-style-1 btn-white btn-sm" href="#" data-toggle="tooltip" title="" data-original-title="You currently have 290 Reward points to spend"><i class="fa fa-award text-md"></i>&nbsp;290 points</a> -->
                    </div>
                    <div class="author-card-profile">
                        <div class="author-card-avatar"><img src="<?php echo USER_AVATAR_URL; ?>" alt="<?php echo $_SESSION['user']->fullName; ?>">
                        </div>
                        <div class="author-card-details">
                            <h5 class="author-card-name text-lg"><?php echo $_SESSION['user']->fullName; ?></h5><span class="author-card-position">Joined <?php echo date('F d, Y', strtotime($_SESSION['user']->joinDate)) ?></span>
                        </div>
                    </div>
                </div>
                <div class="wizard">
                    <nav class="list-group list-group-flush">
                        <a class="list-group-item active" href="#">
                            <div class="d-flex justify-content-between align-items-center">
                                <div><i class="fa fa-shopping-bag mr-1 text-muted"></i>
                                    <div class="d-inline-block font-weight-medium text-uppercase"><?php echo _t('ordersList'); ?></div>
                                </div><span class="badge badge-secondary"><?php echo count($this->saleOrders); ?></span>
                            </div>
                        </a>
                        <a class="list-group-item" href="<?php echo MAIN_URL . 'my-profile'; ?>"><i class="fa fa-user text-muted"></i><?php echo _t('myProfile'); ?></a>
                        <!-- <a class="list-group-item" href="#"><i class="fa fa-map-marker text-muted"></i>Addresses</a> -->
                        <a class="list-group-item" href="#">
                            <div class="d-flex justify-content-between align-items-center">
                                <div><i class="fa fa-heart mr-1"></i>
                                    <div class="d-inline-block font-weight-medium text-uppercase"><?php echo _t('myWishlist'); ?></div>
                                </div><span class="badge badge-secondary"><?php echo count($_SESSION['user']->wishlist); ?></span>
                            </div>
                        </a>
                        <!-- <a class="list-group-item" href="#">
                            <div class="d-flex justify-content-between align-items-center">
                                <div><i class="fa fa-tag mr-1 text-muted"></i>
                                    <div class="d-inline-block font-weight-medium text-uppercase">My Tickets</div>
                                </div><span class="badge badge-secondary">4</span>
                            </div>
                        </a> -->
                    </nav>
                </div>
            </div>
            <!-- Wishlist-->
            <div class="col-lg-8 pb-5">
                <div class="vendor-page-wrapper">
                    <div class="filters-wrap">
                        <div class="row">
                            <div class="col-md-12">
                                <form class="form-inline" action="">
                                    <label for="" class="main"><?php echo _t('filterBy');?>:</label>
                                    <div>
                                        <label for="pwd">Date:</label>
                                        <input type="text" class="form-control date" name="date" value="<?php echo $date; ?>">
                                    </div>
                                    <div>
                                        <label for="pwd">Status:</label>
                                        <select name="status" class="custom-select form-control">
                                            <option value="" selected>Select Status</option>
                                            <option value="pending" <?php if ($this->status == 'pending') {
                                                                        echo 'selected';
                                                                    } ?>>PENDING</option>
                                            <option value="complete" <?php if ($this->status == 'complete') {
                                                                            echo 'selected';
                                                                        } ?>>COMPLETE</option>
                                            <option value="in-progress" <?php if ($this->status == 'in-progress') {
                                                                            echo 'selected';
                                                                        } ?>>IN PROGRESS</option>
                                        </select>
                                    </div>
                                    <button type="submit" class="btn apply-btn">SEARCH</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="orders-wrap">
                        <?php foreach ($this->saleOrders as $saleOrder) {
                            $saleOrderItemsMySqlExtDAO = new SaleOrderItemMySqlExtDAO();
                            $saleOrderItems = $saleOrderItemsMySqlExtDAO->getSaleOrderItems($saleOrder->id);
                            echo DesignController::customerOrderItem($saleOrder, $saleOrderItems);
                        } ?>
                    </div>
                    <div class="pagination-wrap">
                        <div id="product-pagination" class="text-center"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>