<div class="main-wrapper pt30">
    <div class="container mb-4">
        <div class="row">
            <div class="col-lg-4 pb-5">
                <!-- Account Sidebar-->
                <div class="author-card pb-3">
                    <div class="author-card-cover" style="background-image: url(<?php echo USER_AVATAR_BG_URL; ?>);">
                        <!-- <a class="btn btn-style-1 btn-white btn-sm" href="#" data-toggle="tooltip" title="" data-original-title="You currently have 290 Reward points to spend"><i class="fa fa-award text-md"></i>&nbsp;290 points</a> -->
                    </div>
                    <div class="author-card-profile">
                        <div class="author-card-avatar"><img src="<?php echo USER_AVATAR_URL; ?>" alt="<?php echo $_SESSION['user']->fullName; ?>">
                        </div>
                        <div class="author-card-details">
                            <h5 class="author-card-name text-lg"><?php echo $_SESSION['user']->fullName; ?></h5><span class="author-card-position">Joined <?php echo date('F d, Y', strtotime($_SESSION['user']->joinDate)) ?></span>
                        </div>
                    </div>
                </div>
                <div class="wizard">
                    <nav class="list-group list-group-flush">
                        <a class="list-group-item active" href="#">
                            <div class="d-flex justify-content-between align-items-center">
                                <div><i class="fa fa-shopping-bag mr-1 text-muted"></i>
                                    <div class="d-inline-block font-weight-medium text-uppercase">Orders List</div>
                                </div><span class="badge badge-secondary">6</span>
                            </div>
                        </a><a class="list-group-item" href="#"><i class="fa fa-user text-muted"></i>Profile Settings</a><a class="list-group-item" href="#"><i class="fa fa-map-marker text-muted"></i>Addresses</a>
                        <a class="list-group-item" href="<?php echo MAIN_URL . 'my-wishlist'; ?>">
                            <div class="d-flex justify-content-between align-items-center">
                                <div><i class="fa fa-heart mr-1"></i>
                                    <div class="d-inline-block font-weight-medium text-uppercase">My Wishlist</div>
                                </div><span class="badge badge-secondary"><?php echo count($_SESSION['user']->wishlist); ?></span>
                            </div>
                        </a>
                        <a class="list-group-item" href="#">
                            <div class="d-flex justify-content-between align-items-center">
                                <div><i class="fa fa-tag mr-1 text-muted"></i>
                                    <div class="d-inline-block font-weight-medium text-uppercase">My Tickets</div>
                                </div><span class="badge badge-secondary">4</span>
                            </div>
                        </a>
                    </nav>
                </div>
            </div>
            <!-- Wishlist-->
            <div class="col-lg-8 pb-5">
                <div class="edit-profile-wrap vendor-page-wrapper">
                    <form action="<?php echo MAIN_URL . 'add-warehouse' ?>" id="add-warehouse">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6 input-wrap">
                                    <div class="row">
                                        <div class="col-md-12">
                                        <label for="email">*First Name</label>
                                            <input type="text" class="form-control" placeholder="" name="first-name">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6 input-wrap">
                                    <div class="row">
                                        <div class="col-md-12">
                                        <label for="email">*Last Name</label>
                                            <input type="text" class="form-control" placeholder="" name="last-name">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6 input-wrap">
                                    <div class="row">
                                        <div class="col-md-12">
                                        <label for="email">*Email Address</label>
                                            <input type="email" class="form-control" placeholder="" name="email">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6 input-wrap">
                                    <div class="row">
                                        <div class="col-md-12">
                                        <label for="email">*Mobile Number</label>
                                            <input name="mobile" type="text" class="form-control" placeholder="" id="mobile-number" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn submit-btn">SAVE</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>