<?php
    use Application\Controller\ProductController;
?>
<div class="main-wrapper pt30">
    <div class="container mb-4">
        <div class="row">
            <div class="col-lg-4 pb-5">
                <!-- Account Sidebar-->
                <div class="author-card pb-3">
                    <div class="author-card-cover" style="background-image: url(<?php echo USER_AVATAR_BG_URL; ?>);">
                        <!-- <a class="btn btn-style-1 btn-white btn-sm" href="#" data-toggle="tooltip" title="" data-original-title="You currently have 290 Reward points to spend"><i class="fa fa-award text-md"></i>&nbsp;290 points</a> -->
                    </div>
                    <div class="author-card-profile">
                        <div class="author-card-avatar"><img src="<?php echo USER_AVATAR_URL; ?>" alt="<?php echo $_SESSION['user']->fullName; ?>">
                        </div>
                        <div class="author-card-details">
                            <h5 class="author-card-name text-lg"><?php echo $_SESSION['user']->fullName; ?></h5><span class="author-card-position">Joined <?php echo date('F d, Y', strtotime($_SESSION['user']->joinDate)) ?></span>
                        </div>
                    </div>
                </div>
                <div class="wizard">
                    <nav class="list-group list-group-flush">
                        <a class="list-group-item" href="<?php echo MAIN_URL.'my-orders';?>">
                            <div class="d-flex justify-content-between align-items-center">
                                <div><i class="fa fa-shopping-bag mr-1 text-muted"></i>
                                    <div class="d-inline-block font-weight-medium text-uppercase"><?php echo _t('ordersList');?></div>
                                </div><span class="badge badge-secondary"><?php echo $this->saleOrdersCount;?></span>
                            </div>
                        </a>
                        <a class="list-group-item" href="<?php echo MAIN_URL.'my-profile';?>"><i class="fa fa-user text-muted"></i><?php echo _t('myProfile');?></a>
                        <!-- <a class="list-group-item" href="#"><i class="fa fa-map-marker text-muted"></i>Addresses</a> -->
                        <a class="list-group-item active" href="#">
                            <div class="d-flex justify-content-between align-items-center">
                                <div><i class="fa fa-heart mr-1"></i>
                                    <div class="d-inline-block font-weight-medium text-uppercase"><?php echo _t('myWishlist');?></div>
                                </div><span class="badge badge-secondary"><?php echo count($_SESSION['user']->wishlist);?></span>
                            </div>
                        </a>
                        <!-- <a class="list-group-item" href="#">
                            <div class="d-flex justify-content-between align-items-center">
                                <div><i class="fa fa-tag mr-1 text-muted"></i>
                                    <div class="d-inline-block font-weight-medium text-uppercase">My Tickets</div>
                                </div><span class="badge badge-secondary">4</span>
                            </div>
                        </a> -->
                    </nav>
                </div>
            </div>
            <!-- Wishlist-->
            <div class="col-lg-8 pb-5">
                <!-- Item-->
                <?php foreach ($this->wishlist as $row) {
                    $class = "text-warning";
                    $text = "Out of Stock";
                    $image = ($row->image != "") ? BASE_URL . upload_image_dir . $row->image : PRODUCT_PLACEHOLDER_THUMBNAIL_URL;
                    if ($row->qty > 0) {
                        $class = "text-success";
                        $text = "In Stock";
                    }
                ?>
                    <div class="cart-item d-md-flex justify-content-between"><span class="remove-item wishlist-add" data-item-id="<?php echo $row->id;?>"><i class="fa fa-times"></i></span>
                        <div class="px-3 my-3">
                            <a class="cart-item-product" href="<?php echo MAIN_URL.'product/'.$row->slug;?>">
                                <div class="cart-item-product-thumb"><img src="<?php echo $image; ?>" alt="Product"></div>
                                <div class="cart-item-product-info">
                                    <h4 class="cart-item-product-title"><?php echo $row->title; ?></h4>
                                    <div class="text-lg text-body font-weight-medium pb-1"><?php echo _t('lbp');?> <?php echo ProductController::getFinalPrice($row->regularPrice, $row->salePrice); ?></div><span>Availability: <span class="<?php echo $class; ?> font-weight-medium"><?php echo $text; ?></span></span>
                                </div>
                            </a>
                        </div>
                    </div>
                <?php } ?>
                <!-- <div class="custom-control custom-checkbox">
                    <input class="custom-control-input" type="checkbox" checked="" id="inform-me">
                    <label class="custom-control-label" for="inform-me">Inform me when item from my wishlist is available</label>
                </div> -->
            </div>
        </div>
    </div>
</div>