<div class="main-wrapper shopping-cart pt30">
    <div class="container">
        <div class="row">
            <div class="col-md-12"><h3 style="width: 100%;text-align: center;">Payment Failed</h3></div>
            <div class="col-md-12 text-center checkout-btn-wrap">
                <a href="<?php echo MAIN_URL . 'checkout'; ?>" class="" id="checkout-btn">Back To Checkout</a>
            </div>
        </div>
    </div>
</div>