<?php

?>
<div class="main-wrapper forgot-password reset-password pt30">
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <!-- Modal body -->
                <div class="modal-body">
                    <div class="modal-title">Reset Password!</div>
                    <div class="modal-subtitle">Enter your new password.</div>

                    <div class="modal-form">
                        <form action="<?php echo MAIN_URL . 'reset-password/' . $this->userType; ?>" id="reset-form">
                        <input type="hidden" value="<?php echo $_GET['activationCode'];?>" name="activationCode">
                            <div class="notice-area"></div>
                            <div class="form-group">
                                <input type="password" class="form-control" placeholder="Enter Password*" id="" name="password" autocomplete="new-password">
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" placeholder="Confirm Password*" id="" name="confirm-password" autocomplete="new-password">
                            </div>
                            <div class="centered-button">
                                <button type="submit" class="btn">UPDATE</button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<?php //$redirectUrl = urlencode($_GET['redirectUrl']);
?>
<script>
    // const redirectUrl = '<?php //echo $redirectUrl;
                            ?>';
    // $(function(){
    //     $('input[name="redirectUrl"]').val(redirectUrl);
    // });
</script>