<?php

use Application\Controller\CategoryController;
use Application\Controller\HelperController;
use Application\Controller\LanguageController;

global $categories;
$brandCategoryMappingMySqlExtDAO = new BrandCategoryMappingMySqlExtDAO();
$itemBrandMySqlExtDAO = new ItemBrandMySqlExtDAO();
$distinctBrandCategories = $brandCategoryMappingMySqlExtDAO->getDistinctCategories();
$lang = LanguageController::getLanguage();
?>

<div class="lower-menu d-none d-sm-block">
    <div class="container">
        <div class="mega-menu">
            <nav class="navbar navbar-expand-md yamm">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse-grid" aria-controls="navbar-collapse-grid" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div id="navbar-collapse-grid" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav nav-fill w-100">
                        <!-- Grid 12 Menu -->
                        <?php foreach ($categories as $row) {
                            $categoryName = CategoryController::categoryName($row->name, $row->arabicName);
                        ?>
                            <li class="nav-item dropdown yamm-fw category-dropdown"><a href="<?php echo MAIN_URL . $lang . '/products/' . $row->slug; ?>" class="nav-link"><?php echo $categoryName ?><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li class="grid-list">
                                        <div class="grid-container card-columns">
                                            <?php foreach ($row->subcategories as $row1) {
                                                $categoryName1 = CategoryController::categoryName($row1->name, $row1->arabicName); ?>
                                                <div class="grid-item card">
                                                    <div class="main-cat-name"><a href="<?php echo MAIN_URL . $lang . '/products/' . $row->slug . "/" . $row1->slug; ?>"><?php echo $categoryName1; ?></a></div>
                                                    <ul class="subcategories">
                                                        <?php foreach ($row1->subsubcategories as $row2) {
                                                            $categoryName2 = CategoryController::categoryName($row2->name, $row2->arabicName); ?>
                                                            <li><a href="<?php echo MAIN_URL . $lang . '/products/' . $row->slug . "/" . $row1->slug . "/" . $row2->slug; ?>"><?php echo $categoryName2; ?></a></li>
                                                        <?php } ?>
                                                    </ul>
                                                </div>
                                            <?php } ?>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        <?php } ?>
                        <!--
              <Aside>Menu </Aside>
              -->
                        <li class="nav-item dropdown yamm-fw brands-dropdown" id="brands-li"><a href="#" data-toggle="dropdown" class="nav-link  dropdown-toggle"><?php echo _t('shopByBrand'); ?><b class="caret"></b></a>
                            <div class="dropdown-menu">
                                <form>
                                    <div>
                                        <div class="brands-slider-container">
                                            <?php
                                            $brands = $itemBrandMySqlExtDAO->queryByShowInMenu(1); ?>
                                            <div class="brands-slider" id="brands-slider">
                                                <?php foreach ($brands as $brand) { ?>
                                                    <div>
                                                        <a href="<?php echo MAIN_URL . 'products' . "?brand=" . $brand->id; ?>"><img src="<?php echo HelperController::getImageUrl($brand->image); ?>" /></a>
                                                    </div>
                                                <?php } ?>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>
                        <!--
              <Nesting>Menu </Nesting>
              -->
                        <li class="nav-item dropdown yamm-fw promotions-link">
                            <a href="<?php echo MAIN_URL . $lang . '/promotions'; ?>" class="nav-link"><?php echo _t('promotions'); ?></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
</div>