<?php
global $categories;
?>
<div class="mobile-menu d-block d-sm-none">
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
            <a href="#" class="navbar-brand font-weight-bold">&nbsp;</a>
            <button type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbars" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler">
                <!-- <span class="navbar-toggler-icon"></span> -->
                <i class="fas fa-bars" style="color:#fff; font-size:28px;"></i>
            </button>


            <div id="navbarContent" class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                   <?php /* <!-- Level one dropdown -->
                    <li class="nav-item dropdown">
                        <a id="dropdownMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Dropdown</a>
                        <ul aria-labelledby="dropdownMenu1" class="dropdown-menu border-0">
                            <li><a href="#" class="dropdown-item">Some action </a></li>
                            <li><a href="#" class="dropdown-item">Some other action</a></li>
                            <!-- Level two dropdown-->
                            <li class="dropdown-submenu">
                                <a id="dropdownMenu2" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-item dropdown-toggle">Hover for action</a>
                                <ul aria-labelledby="dropdownMenu2" class="dropdown-menu border-0">
                                    <li>
                                        <a tabindex="-1" href="#" class="dropdown-item">level 2</a>
                                    </li>

                                    <li><a href="#" class="dropdown-item">level 2</a></li>
                                    <li><a href="#" class="dropdown-item">level 2</a></li>
                                </ul>
                            </li>
                            <!-- End Level two -->
                        </ul>
                    </li>
                    <!-- End Level one -->*/?>

                    <?php foreach ($categories as $row) { ?>
                        <li class="nav-item dropdown">
                            <a id="dropdownMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle"><?php echo $row->name; ?></a>
                            <ul aria-labelledby="dropdownMenu1" class="dropdown-menu border-0">
                                <!-- <li><a href="#" class="dropdown-item">Some action </a></li>
                                <li><a href="#" class="dropdown-item">Some other action</a></li> -->
                                <?php foreach ($row->subcategories as $row1) { ?>
                                    <!-- Level two dropdown-->
                                    <li class="dropdown-submenu">
                                        <a id="dropdownMenu2" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-item dropdown-toggle"><?php echo $row1->name ?></a>
                                        <ul aria-labelledby="dropdownMenu2" class="dropdown-menu border-0">
                                        <?php foreach ($row1->subsubcategories as $row2) { ?>
                                            <li><a href="<?php echo MAIN_URL . 'products/' . $row->slug . "/" . $row1->slug . "/" . $row2->slug; ?>" class="dropdown-item"><?php echo $row2->name;?></a></li>
                                            <?php }?>
                                        </ul>
                                    </li>
                                    <!-- End Level two -->
                                <?php } ?>

                            </ul>
                        </li>
                    <?php } ?>


                    <li class="nav-item"><a href="<?php echo MAIN_URL.'promotions'?>" class="nav-link">Promotions</a></li>
                    <li class="nav-item"><a href="<?php echo MAIN_URL.'latest-arrivals'?>" class="nav-link">Latest products</a></li>
                    <li class="nav-item"><a href="<?php echo MAIN_URL.'todays-deals'?>" class="nav-link">Todays Deals</a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>