<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use Application\Controller\DesignController;
use Application\Controller\HelperController;

?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <?php echo DesignController::mainTitle('SHOP BY CATEGORIES') ?>
        </div>
        <div class="col-md-12">
            <div class="categories-slider-wrapper">
                <div id="categories-slider">
                    <?php foreach($this->featuredCategories as $cat){?>
                    <div>
                        <div class="cat-img"><a href="#"><img src="<?php echo HelperController::getImageUrl($cat->image);?>" /></a></div>
                        <div class="cat-title"><a href="#"><?php echo $cat->name;?></a></div>
                    </div>
                    <?php }?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="full-width base-color with-slider">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="special-tags">
                    <ul>
                        <li class="active" id="daily-deals"><a href="#">DAILY DEALS</a></li>
                        <li id="picked-for-you"><a href="#">PICKED FOR YOU</a></li>
                        <li id="best-offers"><a href="#">BEST OFFERS</a></li>
                    </ul>
                </div>
                <div class="special-tags-slider-container">
                    <div class="special-tags-slider" id="special-tags-slider-daily-deals">
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                    </div>
                    <div class="special-tags-slider" id="special-tags-slider-best-offers">
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                    </div>
                    <div class="special-tags-slider" id="special-tags-slider-picked-for-you">
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                        <div>
                            <?php echo DesignController::item(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php if ($this->ads) {
        echo $this->partial('layout/ads');
    } ?>