<?php
ini_set('display_errors', 1);
error_reporting(E_ALL);
// Create connection
$cat3 = "Accessoriesa";
$cat2 = "TV";
$cat1 = "Electronics";
function getCategory($cat1 = "", $cat2 = "", $cat3 = "")
{
    $conn = ConnectionFactory::getConnection();
    // Check connection
    if ($conn->connect_error) {
        die("Connection failed: " . $conn->connect_error);
    }
    $sql = "SELECT
        c.`id`
        FROM
        item_category a
        LEFT OUTER JOIN item_category b
        ON a.`id` = b.`parent_id`
        LEFT OUTER JOIN item_category c
        ON b.`id` = c.`parent_id`
        WHERE c.`name` IS NOT NULL
        AND c.`name` = '$cat3' AND b.`name` = '$cat2' AND a.`name` = '$cat1'
        ORDER BY c.`name` ASC LIMIT 1 OFFSET 0";
    $rows = $conn->query($sql);
    $conn->close();
    if ($rows->num_rows > 0) {
        // output data of each row
        $row  =  $rows->fetch_object();
        return $row->id;
    } else {
        return 0;
    }
}
echo getCategory($cat1, $cat2, $cat3);
